### ISSUE TITLE
How to use when login?

### ISSUE THREAD

**Issue by williamokano** [kkito/transmission-rpc#1]
I don't have a whitelist enabled, how could I use the client using my login? Thanks

**Comment by kkito** [comment]
Login is not implemented yet.

**Comment by kkito** [comment]
It's essential, i will work on it.

**Comment by williamokano** [comment]
Hi, thanks. On my project I did an workaround using axios interceptors, but I haven't time to implement it on your lib. Thanks for the answer and for this lib :)

**Comment by kkito** [comment]
Basic auth is available now from v0.2.0
f911fd8
